### ISSUE TITLE
Link "zero to hero" dbt is not working

### ISSUE THREAD

**Issue by andriimazur93** [Hiflylabs/awesome-dbt#43]
This link [Zero to Hero dbt](https://dbtlearn.com/) in getting started section is not working anymore.

**Comment by nszoni** [comment]
@zsombor-flds let's create a bot for checking awesome links (https://github.com/dkhamsing/awesome_bot)

**Comment by zsombor-flds** [comment]
Awesome idea, solved by this [PR](https://github.com/Hiflylabs/awesome-dbt/pull/56)
