### ISSUE TITLE
Add Tabula to Integrations section

### ISSUE THREAD

**Issue by Anastasia-Antonova-retable** [Hiflylabs/awesome-dbt#68]
A new free tool to visualize dbt packages to handle big data with AI

[Tabula](tabula.io) - dbt-compatible AI platform to model data in a low-code UI

**Comment by zsombor-flds** [comment]
Hi @Anastasia-Antonova-retable,
Thank you for the proposal for Tabula.  I added extended possible Integrations to the list with it.
Related PR: https://github.com/Hiflylabs/awesome-dbt/pull/71/files.

**Comment by Anastasia-Antonova-retable** [comment]
Cool cool thanks!!
